namespace: nicr9
name: firefox
version: 1.0.0
readme: README.md
authors:
- Nic Roland <nicroland9@gmail.com>
license:
- MIT
description: install and configure Firefox
tags: []
dependencies: {}
repository: https://github.com/nicr9/anisible-firefox
documentation: https://github.com/nicr9/anisible-firefox
homepage: https://github.com/nicr9/anisible-firefox
issues: https://github.com/nicr9/anisible-firefox/issues
build_ignore: []

